
<?php

function property_tax_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'property_tax/d3';
  $attachments['#attached']['library'][] = 'property_tax/bootstrap-slider';
  $attachments['#attached']['library'][] = 'property_tax/ptc';
  $attachments['#attached']['library'][] = 'property_tax/chosen';
  $attachments['#attached']['library'][] = 'property_tax/d3fc';
}

?>
